admins:
  - email: 'andrez47@gmail.com'
phases:
  - code: 'A'
    level: 1
    small_points: 1
    big_points: 3
    active: true
  - code: 'B'
    level: 1
    small_points: 1
    big_points: 3
    active: true
  - code: 'C'
    level: 1
    small_points: 1
    big_points: 3
    active: true
  - code: 'D'
    level: 1
    small_points: 1
    big_points: 3
    active: true
  - code: 'E'
    level: 1
    small_points: 1
    big_points: 3
    active: true
  - code: 'F'
    level: 1
    small_points: 1
    big_points: 3
    active: true
  - code: 'G'
    level: 1
    small_points: 1
    big_points: 3
    active: true
  - code: 'H'
    level: 1
    small_points: 1
    big_points: 3
    active: true
  - code: 'round_of_16'
    level: 2
    small_points: 2
    big_points: 5
    active: false
  - code: 'quarter_finals'
    level: 3
    small_points: 3
    big_points: 7
    active: false
  - code: 'semi_finals'
    level: 4
    small_points: 4
    big_points: 9
    active: false
  - code: 'third_place'
    level: 5
    small_points: 5
    big_points: 11
    active: false
  - code: 'final'
    level: 6
    small_points: 6
    big_points: 13
    active: false
teams:
  - code: 'arg'
    group: 'D'
  - code: 'aus'
    group: 'C'
  - code: 'bel'
    group: 'G'
  - code: 'bra'
    group: 'E'
  - code: 'col'
    group: 'H'
  - code: 'crc'
    group: 'E'
  - code: 'cro'
    group: 'D'
  - code: 'den'
    group: 'C'
  - code: 'egy'
    group: 'A'
  - code: 'eng'
    group: 'G'
  - code: 'esp'
    group: 'B'
  - code: 'fra'
    group: 'C'
  - code: 'ger'
    group: 'F'
  - code: 'irn'
    group: 'B'
  - code: 'isl'
    group: 'D'
  - code: 'jpn'
    group: 'H'
  - code: 'kor'
    group: 'F'
  - code: 'ksa'
    group: 'A'
  - code: 'mar'
    group: 'B'
  - code: 'mex'
    group: 'F'
  - code: 'nga'
    group: 'D'
  - code: 'pan'
    group: 'G'
  - code: 'per'
    group: 'C'
  - code: 'pol'
    group: 'H'
  - code: 'por'
    group: 'B'
  - code: 'rus'
    group: 'A'
  - code: 'sen'
    group: 'H'
  - code: 'srb'
    group: 'E'
  - code: 'sui'
    group: 'E'
  - code: 'swe'
    group: 'F'
  - code: 'tun'
    group: 'G'
  - code: 'uru'
    group: 'A'
matches:
  - date: '2018-06-14 09:00 CST'
    team1: rus
    team2: ksa
    phase: A
  - date: '2018-06-15 06:00 CST'
    team1: egy
    team2: uru
    phase: A
  - date: '2018-06-15 09:00 CST'
    team1: mar
    team2: irn
    phase: B
  - date: '2018-06-15 12:00 CST'
    team1: por
    team2: esp
    phase: B
  - date: '2018-06-16 04:00 CST'
    team1: fra
    team2: aus
    phase: C
  - date: '2018-06-16 07:00 CST'
    team1: arg
    team2: isl
    phase: D
  - date: '2018-06-16 10:00 CST'
    team1: per
    team2: den
    phase: C
  - date: '2018-06-16 13:00 CST'
    team1: cro
    team2: nga
    phase: D
  - date: '2018-06-17 06:00 CST'
    team1: crc
    team2: srb
    phase: E
  - date: '2018-06-17 09:00 CST'
    team1: ger
    team2: mex
    phase: F
  - date: '2018-06-17 12:00 CST'
    team1: bra
    team2: sui
    phase: E
  - date: '2018-06-18 06:00 CST'
    team1: swe
    team2: kor
    phase: F
  - date: '2018-06-18 09:00 CST'
    team1: bel
    team2: pan
    phase: G
  - date: '2018-06-18 12:00 CST'
    team1: tun
    team2: eng
    phase: G
  - date: '2018-06-19 06:00 CST'
    team1: col
    team2: jpn
    phase: H
  - date: '2018-06-19 09:00 CST'
    team1: pol
    team2: sen
    phase: H
  - date: '2018-06-19 12:00 CST'
    team1: rus
    team2: egy
    phase: A
  - date: '2018-06-20 06:00 CST'
    team1: por
    team2: mar
    phase: B
  - date: '2018-06-20 09:00 CST'
    team1: uru
    team2: ksa
    phase: A
  - date: '2018-06-20 12:00 CST'
    team1: irn
    team2: esp
    phase: B
  - date: '2018-06-21 06:00 CST'
    team1: den
    team2: aus
    phase: C
  - date: '2018-06-21 09:00 CST'
    team1: fra
    team2: per
    phase: C
  - date: '2018-06-21 12:00 CST'
    team1: arg
    team2: cro
    phase: D
  - date: '2018-06-22 06:00 CST'
    team1: bra
    team2: crc
    phase: E
  - date: '2018-06-22 09:00 CST'
    team1: nga
    team2: isl
    phase: D
  - date: '2018-06-22 12:00 CST'
    team1: srb
    team2: sui
    phase: E
  - date: '2018-06-23 06:00 CST'
    team1: bel
    team2: tun
    phase: G
  - date: '2018-06-23 09:00 CST'
    team1: kor
    team2: mex
    phase: F
  - date: '2018-06-23 12:00 CST'
    team1: ger
    team2: swe
    phase: F
  - date: '2018-06-24 06:00 CST'
    team1: eng
    team2: pan
    phase: G
  - date: '2018-06-24 09:00 CST'
    team1: jpn
    team2: sen
    phase: H
  - date: '2018-06-24 12:00 CST'
    team1: pol
    team2: col
    phase: H
  - date: '2018-06-25 08:00 CST'
    team1: uru
    team2: rus
    phase: A
  - date: '2018-06-25 08:00 CST'
    team1: ksa
    team2: egy
    phase: A
  - date: '2018-06-25 12:00 CST'
    team1: irn
    team2: por
    phase: B
  - date: '2018-06-25 12:00 CST'
    team1: esp
    team2: mar
    phase: B
  - date: '2018-06-26 08:00 CST'
    team1: den
    team2: fra
    phase: C
  - date: '2018-06-26 08:00 CST'
    team1: aus
    team2: per
    phase: C
  - date: '2018-06-26 12:00 CST'
    team1: nga
    team2: arg
    phase: D
  - date: '2018-06-26 12:00 CST'
    team1: isl
    team2: cro
    phase: D
  - date: '2018-06-27 08:00 CST'
    team1: mex
    team2: swe
    phase: F
  - date: '2018-06-27 08:00 CST'
    team1: kor
    team2: ger
    phase: F
  - date: '2018-06-27 12:00 CST'
    team1: srb
    team2: bra
    phase: E
  - date: '2018-06-27 12:00 CST'
    team1: sui
    team2: crc
    phase: E
  - date: '2018-06-28 08:00 CST'
    team1: jpn
    team2: pol
    phase: H
  - date: '2018-06-28 08:00 CST'
    team1: sen
    team2: col
    phase: H
  - date: '2018-06-28 12:00 CST'
    team1: pan
    team2: tun
    phase: G
  - date: '2018-06-28 12:00 CST'
    team1: eng
    team2: bel
    phase: G
  - date: '2018-06-30 08:00 CST'
    phase: round_of_16
    team1_label: 1C
    team2_label: 2D
  - date: '2018-06-30 12:00 CST'
    phase: round_of_16
    team1_label: 1A
    team2_label: 2B
  - date: '2018-07-01 08:00 CST'
    phase: round_of_16
    team1_label: 1B
    team2_label: 2A
  - date: '2018-07-01 12:00 CST'
    phase: round_of_16
    team1_label: 1D
    team2_label: 2C
  - date: '2018-07-02 08:00 CST'
    phase: round_of_16
    team1_label: 1E
    team2_label: 2F
  - date: '2018-07-02 12:00 CST'
    phase: round_of_16
    team1_label: 1G
    team2_label: 2H
  - date: '2018-07-03 08:00 CST'
    phase: round_of_16
    team1_label: 1F
    team2_label: 2E
  - date: '2018-07-03 12:00 CST'
    phase: round_of_16
    team1_label: 1H
    team2_label: 2G
  - date: '2018-07-06 08:00 CST'
    phase: quarter_finals
    team1_label: W49
    team2_label: W50
  - date: '2018-07-06 12:00 CST'
    phase: quarter_finals
    team1_label: W53
    team2_label: W54
  - date: '2018-07-07 08:00 CST'
    phase: quarter_finals
    team1_label: W55
    team2_label: W56
  - date: '2018-07-07 12:00 CST'
    phase: quarter_finals
    team1_label: W51
    team2_label: W52
  - date: '2018-07-10 12:00 CST'
    phase: semi_finals
    team1_label: W57
    team2_label: W58
  - date: '2018-07-11 12:00 CST'
    phase: semi_finals
    team1_label: W59
    team2_label: W60
  - date: '2018-07-14 08:00 CST'
    phase: third_place
    team1_label: L61
    team2_label: L62
  - date: '2018-07-15 09:00 CST'
    phase: final
    team1_label: W61
    team2_label: W62
